version = 0.1
[default.deploy.parameters]
stack_name = "trueachievements"
resolve_s3 = true
s3_prefix = "trueachievements"
region = "us-east-2"
confirm_changeset = true
capabilities = "CAPABILITY_IAM"
parameter_overrides = "CognitoDomain=\"project-trueachievements-allen-potts\" S3Bucket=\"nss-s3-c03-u7-capstone-allen.potts\" FrontendDeployment=\"remote\""
image_repositories = []
